[build-system]
requires = ["uv_build>=0.11.17,<0.12.0"]
build-backend = "uv_build"

[project]
name="statpy"
version = "2.0.0"
description = "Database system with statistics library for analysing lattice QCD simulation data."
readme="README.md"
requires-python=">=3.12"
authors = [
    {name="Sebastian Spiegel", email="sebastian.spiegel@physik.uni-regensburg.de"}
]
dependencies=["numpy<2.4", "scipy", "iminuit", "numba", "h5py"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
