[build-system]
requires = ["uv_build>=0.11.17,<0.12.0"]
build-backend = "uv_build"

[project]
name="statpy"
version = "2.0.0"
description = "Python toolkit targeted at MCMC data analysis in the context of lattice QCD."
readme="README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python=">=3.12"
authors = [
    {name="Sebastian Spiegel", email="spieseba@mailbox.org"}
]
dependencies=["numpy<2.4", "scipy", "iminuit", "numba", "h5py"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
