"""Correlator analysis: primitives, fit models, fits, FitConfig."""
from statpy.qcd.correlator.averaging import (
    meson_fold_correlator_entry,
    obc_meson_boundary_average,
    obc_meson_correlator_average,
    pbc_correlator_average,
)
from statpy.qcd.correlator.fits import (
    FitConfig,
    FitTags,
    PlateauTooShortError,
    correlator_combined_fit,
    excited_contributions_fit,
    fit_bss,
    fit_jks,
    fit_mean,
    get_p0_guess,
    ground_state_fit,
)
from statpy.qcd.correlator.models import (
    combined_corr_chi2,
    const_chi2,
    const_model,
    const_plus_exp,
    const_plus_exp_chi2,
    cosh_chi2,
    cosh_model,
    double_cosh_chi2,
    double_cosh_model,
    double_exp_chi2,
    double_exp_model,
    double_sinh_chi2,
    double_sinh_model,
    exp_chi2,
    exp_model,
    fit_model_dict,
    sinh_chi2,
    sinh_model,
)
from statpy.qcd.correlator.primitives import (
    Aeff_cosh,
    Aeff_exp,
    Aeff_sinh,
    binned_tag,
    get_tmax_signal_to_noise,
    meff_cosh,
    meff_cosh_midpoint,
    meff_exp_forward,
    meff_exp_symmetric,
    meff_sinh,
    meson_fold_correlator,
)
